using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.10.0
[assembly: AssemblyInformationalVersion("0.10.0")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyFileVersion("0.10.40401.1345")] // algorithm: HumanReadable2SlotTimestampGenerator
[assembly: AssemblyConfiguration("Release (on UTC2014-04-01T13:45:14 by imrep at DELL688)")] // algorithm: HumanReadableBuildInfoGenerator
