using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.10.0
[assembly: AssemblyInformationalVersion("0.10.0")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyFileVersion("0.10.50216.1132")] // algorithm: HumanReadable2SlotTimestampGenerator
[assembly: AssemblyConfiguration("Release (on UTC2015-02-16T11:32:28 by imrep at DELL688)")] // algorithm: HumanReadableBuildInfoGenerator
